DROP DATABASE IF EXISTS slackoverflow;
CREATE DATABASE slackoverflow;

-- \c  slackoverflow


DROP TABLE IF EXISTS ACCOUNTS CASCADE;
CREATE TABLE ACCOUNTS(
  accountID INT NOT NULL,
  username VARCHAR(45) NOT NULL,
  password VARCHAR(45) NULL,
  PRIMARY KEY (accountID)
);

DROP TYPE IF EXISTS language CASCADE;
CREATE TYPE language AS ENUM('Java','C++','Javascript','CSS');

DROP TABLE IF EXISTS TIPS CASCADE;
CREATE TABLE TIPS(
	accountID INT NOT NULL REFERENCES ACCOUNTS(accountID),
	language language,
	description VARCHAR(255),
  rating INT  NOT NULL
);

DROP TABLE IF EXISTS USERRATINGS CASCADE;
CREATE TABLE USERRATINGS(
accountID INT NOT NULL REFERENCES ACCOUNTS(accountID),
TipID INT NOT NULL,
username VARCHAR(255),
rating_score SMALLINT NOT NULL
);
