DROP DATABASE IF EXISTS slackoverflow;
CREATE DATABASE slackoverflow;

\c  slackoverflow

DROP TABLE IF EXISTS ACCOUNTS CASCADE;
CREATE TABLE ACCOUNTS (
  accountID INT         NOT NULL,
  username  VARCHAR(45) NOT NULL,
  password  VARCHAR(45) NULL,
  PRIMARY KEY (accountID)
);


DROP TABLE IF EXISTS LANGUAGE;
CREATE TABLE LANGUAGE (
  languageID	INT	NOT NULL,
  language VARCHAR(45),
  PRIMARY KEY (languageID)
);

DROP TABLE IF EXISTS TIPS;
CREATE TABLE TIPS (
  tipsID	INT	NOT NULL,
  accountID   INT NOT NULL REFERENCES ACCOUNTS (accountID),
  languageID INT NOT NULL REFERENCES LANGUAGE (languageID),
  description VARCHAR(255),
  rating      INT NOT NULL,
  PRIMARY KEY (tipsID)
);

DROP TABLE IF EXISTS USERRATINGS;
CREATE TABLE USERRATINGS (
  accountID INT      NOT NULL REFERENCES ACCOUNTS (accountID),
  tipsID     INT      NOT NULL REFERENCES TIPS (tipsID),
  PRIMARY KEY (accountID, tipsID)
);
