DROP DATABASE IF EXISTS slackoverflow;
CREATE DATABASE slackoverflow;

\c  slackoverflow

DROP TABLE IF EXISTS ACCOUNTS CASCADE;
CREATE TABLE ACCOUNTS (
  accountID INT         NOT NULL,
  username  VARCHAR(45) NOT NULL,
  password  VARCHAR(45) NULL,
  PRIMARY KEY (accountID)
);


CREATE TYPE LANGUAGE AS ENUM ('Java', 'Javascript', 'PHP');

DROP TABLE IF EXISTS TIPS;
CREATE TABLE TIPS (
  tipsID	INT	NOT NULL,
  accountID   INT NOT NULL REFERENCES ACCOUNTS (accountID),
  language LANGUAGE,
  description VARCHAR(255),
  rating      INT NOT NULL
  PRIMARY KEY (tipsID)
);

DROP TABLE IF EXISTS USERRATINGS;
CREATE TABLE USERRATINGS (
  accountID INT      NOT NULL REFERENCES ACCOUNTS (accountID),
  tipsID     INT      NOT NULL REFERENCES TIPS (tipsID),
  PRIMARY KEY (accountID, tipsID)
);
